[phases.setup]
nixPkgs = ['nodejs_18', 'chromium']

[phases.install]
cmds = [
  'cd backend && npm install --omit=dev'
]

[phases.build]
cmds = []

[start]
cmd = 'cd backend && node src/server.js'
